name: CI

on:
  push:
    paths-ignore:
      - "**.md"
      - "LICENSE"
  pull_request:
    paths-ignore:
      - "**.md"
      - "LICENSE"

jobs:
  amd64_linux_clang:
    runs-on: ubuntu-latest
    env:
      CC: clang
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 1000
      - name: Install Dependencies
        run: sudo apt install -y make clang
      - run: clang --version
      - name: Build moro8
        run: |
          mkdir -p build
          cd build
          cmake .. || (rm -rf * && cmake ..)
          cmake --build .
          make
      - name: Test moro8
        run: |
          cd build
          make test ARGS="-V"
  amd64_linux_gcc:
    runs-on: ubuntu-latest
    env:
      CC: gcc
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 1000
      - name: Install Dependencies
        run: sudo apt install -y make gcc
      - run: gcc --version
      - name: Build moro8
        run: |
          mkdir -p build
          cd build
          cmake .. || (rm -rf * && cmake ..)
          cmake --build .
          make
      - name: Test moro8
        run: |
          cd build
          make test ARGS="-V"
  amd64_macos_clang:
    runs-on: macos-latest
    env:
      CC: clang
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 1000
      - name: Install Dependencies
        run: sudo apt install -y make clang
      - run: clang --version
      - name: Build moro8
        run: |
          mkdir -p build
          cd build
          cmake .. || (rm -rf * && cmake ..)
          cmake --build .
          make
      - name: Test moro8
        run: |
          cd build
          make test ARGS="-V"
  amd64_macos_gcc:
    runs-on: macos-latest
    env:
      CC: gcc
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 1000
      - name: Install Dependencies
        run: sudo apt install -y make gcc
      - run: gcc --version
      - name: Build moro8
        run: |
          mkdir -p build
          cd build
          cmake .. || (rm -rf * && cmake ..)
          cmake --build .
          make
      - name: Test moro8
        run: |
          cd build
          make test ARGS="-V"
  amd64_windows_clang:
    runs-on: windows-2019
    env:
      CC: clang
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 1000
      - name: Install Dependencies
        run: |
          echo "C:\\msys64\\usr\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          pacman --version
          pacman -Sy
          pacman --noconfirm -S pacman-mirrors
          pacman --noconfirm -S mingw64/mingw-w64-x86_64-clang
          echo "C:\\msys64\\mingw64\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: clang --version
      - name: Build moro8
        run: |
          mkdir -p build
          cd build
          cmake .. || (rm -rf * && cmake ..)
          cmake --build .
          make
      - name: Test moro8
        run: |
          cd build
          make test ARGS="-V"
  amd64_windows_gcc:
    runs-on: windows-2019
    env:
      CC: gcc
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 1000
      - name: Install Dependencies
        run: echo "C:\\msys64\\usr\\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - run: gcc --version
      - name: Build moro8
        run: |
          mkdir -p build
          cd build
          cmake .. || (rm -rf * && cmake ..)
          cmake --build .
          make
      - name: Test moro8
        run: |
          cd build
          make test ARGS="-V"
  amd64_windows_vs2019:
    runs-on: windows-2019
    env:
      CC: gcc
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 1000
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Build moro8
        run: |
          mkdir -p build
          cd build
          cmake .. -G "Visual Studio 16 2019" || (rm -rf * && cmake .. -G "Visual Studio 16 2019")
          cmake --build .
          make
      - name: Test moro8
        run: |
          cd build
          make test ARGS="-V"
